apiVersion: v1
kind: Pod
metadata:
  name: server-user-pod
  labels:
    name: server-user-pod
    app: ctse-app

spec:
  containers:
    - name: shop-user-pod
      image: 19980517/ctse-app
      ports:
        - containerPort: 8070
