apiVersion: v1
kind: Service
metadata:
  name: server-user-pod
  labels:
    name: server-user-pod
    app: ctse-app

spec:
  type: LoadBalancer
  ports:
    - port: 8070
      targetPort: 8070
  selector:
    name: server-user-pod
    app: ctse-app
