apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ctse-app
  name: ctse-app
spec:
  ports:
    - port: 8070
      protocol: TCP
      targetPort: 8070
  selector:
    app: ctse-app
status:
  loadBalancer: {}
  # kubectl expose deploy ctse-app --port 3000 --target-port 8070 - service/ctse-app exposed
