name: Docker Build Deploy

on:
  push:
    branches: [main]


env:
  DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  PRODUCT_REPO_NAME: ${{secrets.PRODUCT_REPO_NAME}}

jobs:
  create-user-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Work Dir
        run: |
          echo $DOCKER_USERNAME
          echo $DOCKER_PASSWORD
          echo $PRODUCT_REPO_NAME

      - name: Docker login
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12
          check-latest: true

      - name: Build user service docker image
        run: docker build . --file Dockerfile -t "$DOCKER_USERNAME/$PRODUCT_REPO_NAME:latest"

      - name: Push user service docker image
        run: docker push "$DOCKER_USERNAME/$PRODUCT_REPO_NAME:latest"

  deployment:
    needs: [create-user-image]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12
          check-latest: true

      - name: kubectl - Google Cloud GKE cluster
        uses: ameydev/gke-kubectl-action@master
        env:
          PROJECT_ID: ${{secrets.PROJECT_ID }}
          APPLICATION_CREDENTIALS: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          CLUSTER_NAME: ${{secrets.CLUSTER_NAME }}
          ZONE_NAME: us-central1-c
        with:
          args: apply -f k8s/
